"""A4: calibration settings

Revision ID: 7695b59925d0
Revises: ddcc479bce83
Create Date: 2026-09-08 08:10:04.895313
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '7695b59925d0'
down_revision: str | None = 'ddcc479bce83'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calibration_target_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calibration_reviewer_id', sa.String(length=36), nullable=True))
        # SQLite の batch モードは無名の制約を扱えないため、名前を付ける
        batch_op.create_foreign_key(
            "fk_experiments_calibration_reviewer", 'operators', ['calibration_reviewer_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_constraint("fk_experiments_calibration_reviewer", type_='foreignkey')
        batch_op.drop_column('calibration_reviewer_id')
        batch_op.drop_column('calibration_target_count')

    # ### end Alembic commands ###
