"""初期スキーマ（仕様第9章の全テーブル）

Revision ID: 8ea2e151cb68
Revises: 
Create Date: 2026-09-08 04:12:20.735907
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '8ea2e151cb68'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operators',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('login_name', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_name')
    )
    op.create_table('presets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('settings_json', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('sdk_version', sa.String(length=64), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('price_max_micro_usd', sa.Integer(), nullable=True),
    sa.Column('price_version', sa.String(length=32), nullable=False),
    sa.Column('price_checked_on', sa.String(length=10), nullable=True),
    sa.Column('price_source_url', sa.Text(), nullable=False),
    sa.Column('is_unverified', sa.Boolean(), nullable=False),
    sa.Column('unverified_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('operator_id', sa.String(length=36), nullable=True),
    sa.Column('target_kind', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('before_json', sa.Text(), nullable=True),
    sa.Column('after_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_target', ['target_kind', 'target_id'], unique=False)

    op.create_table('experiments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('purpose_note', sa.Text(), nullable=False),
    sa.Column('cost_cap_micro_usd', sa.Integer(), nullable=True),
    sa.Column('reference_rate_jpy_per_usd', sa.Integer(), nullable=True),
    sa.Column('hourly_wage_jpy', sa.Integer(), nullable=True),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('track', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("track IN ('standard','early_check')", name='ck_experiments_track'),
    sa.ForeignKeyConstraint(['created_by'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idempotency_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('operator_id', sa.String(length=36), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('body_hash', sa.String(length=64), nullable=False),
    sa.Column('result_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operator_id', 'operation', 'key', name='uq_idempotency')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('operator_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subject_tag', sa.String(length=32), nullable=False),
    sa.Column('source_class', sa.String(length=32), nullable=False),
    sa.Column('consent_status', sa.String(length=16), nullable=False),
    sa.Column('consent_obtained_on', sa.String(length=10), nullable=True),
    sa.Column('consent_scope_note', sa.Text(), nullable=False),
    sa.Column('consent_recorded_by', sa.String(length=36), nullable=True),
    sa.Column('external_system', sa.String(length=64), nullable=True),
    sa.Column('external_tenant_id', sa.String(length=64), nullable=True),
    sa.Column('external_user_id', sa.String(length=64), nullable=True),
    sa.Column('external_image_id', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("consent_status IN ('granted','not_required','missing')", name='ck_assets_consent_status'),
    sa.ForeignKeyConstraint(['consent_recorded_by'], ['operators.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['operators.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index('ix_assets_experiment', ['experiment_id'], unique=False)

    op.create_table('asset_variants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('parent_variant_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('storage_key', sa.String(length=64), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('mime', sa.String(length=32), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('submission_storage_key', sa.String(length=64), nullable=True),
    sa.Column('submission_sha256', sa.String(length=64), nullable=True),
    sa.Column('submission_bytes', sa.Integer(), nullable=True),
    sa.Column('edit_types_json', sa.Text(), nullable=False),
    sa.Column('edit_tool', sa.String(length=100), nullable=False),
    sa.Column('edit_note', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('original','processed')", name='ck_variants_kind'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['operators.id'], ),
    sa.ForeignKeyConstraint(['parent_variant_id'], ['asset_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_variants', schema=None) as batch_op:
        batch_op.create_index('ix_variants_asset', ['asset_id'], unique=False)

    op.create_table('comparisons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('variant_id', sa.String(length=36), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('is_blind', sa.Boolean(), nullable=False),
    sa.Column('revealed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revealed_by', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['operators.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revealed_by'], ['operators.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['asset_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('comparison_id', sa.String(length=36), nullable=True),
    sa.Column('variant_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('preset_id', sa.String(length=36), nullable=False),
    sa.Column('preset_snapshot_json', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('attempt_index', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('tech_status', sa.String(length=32), nullable=False),
    sa.Column('error_kind', sa.String(length=64), nullable=True),
    sa.Column('error_note', sa.Text(), nullable=False),
    sa.Column('provider_task_id', sa.String(length=128), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_owner', sa.String(length=128), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumes_quota', sa.Boolean(), nullable=False),
    sa.Column('blind_label', sa.String(length=1), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['comparison_id'], ['comparisons.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['operators.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['generations.id'], ),
    sa.ForeignKeyConstraint(['preset_id'], ['presets.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['asset_variants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_task_id', name='uq_generations_provider_task')
    )
    with op.batch_alter_table('generations', schema=None) as batch_op:
        batch_op.create_index('ix_generations_experiment', ['experiment_id'], unique=False)
        batch_op.create_index('ix_generations_quota', ['experiment_id', 'asset_id', 'provider'], unique=False)
        batch_op.create_index('ix_generations_status_next_check', ['tech_status', 'next_check_at'], unique=False)

    op.create_table('artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('generation_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('storage_key', sa.String(length=64), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('inspection_ok', sa.Boolean(), nullable=False),
    sa.Column('inspection_note', sa.Text(), nullable=False),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index('ix_artifacts_generation', ['generation_id'], unique=False)

    op.create_table('cost_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('generation_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('amount_micro_usd', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('price_version', sa.String(length=32), nullable=False),
    sa.Column('evidence_note', sa.Text(), nullable=False),
    sa.Column('evidence_checked_on', sa.String(length=10), nullable=True),
    sa.Column('recorded_by', sa.String(length=36), nullable=True),
    sa.Column('dedupe_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('estimate','confirmed_manual','failed_unreconciled')", name='ck_cost_entries_kind'),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_cost_entries_dedupe')
    )
    with op.batch_alter_table('cost_entries', schema=None) as batch_op:
        batch_op.create_index('ix_cost_entries_generation', ['generation_id'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('generation_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('score_fidelity', sa.Integer(), nullable=False),
    sa.Column('score_shape', sa.Integer(), nullable=False),
    sa.Column('score_color', sa.Integer(), nullable=False),
    sa.Column('score_appeal', sa.Integer(), nullable=False),
    sa.Column('score_mobile', sa.Integer(), nullable=True),
    sa.Column('mobile_checked', sa.Boolean(), nullable=False),
    sa.Column('defect_tags_json', sa.Text(), nullable=False),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('work_seconds', sa.Integer(), nullable=False),
    sa.Column('was_blind', sa.Boolean(), nullable=False),
    sa.Column('is_calibration', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("verdict IN ('unreviewed','pass','retry_recommended','unsuitable')", name='ck_reviews_verdict'),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generation_id', 'reviewer_id', 'revision', name='uq_reviews_revision')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index('ix_reviews_generation', ['generation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_reviews_generation')

    op.drop_table('reviews')
    with op.batch_alter_table('cost_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_cost_entries_generation')

    op.drop_table('cost_entries')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index('ix_artifacts_generation')

    op.drop_table('artifacts')
    with op.batch_alter_table('generations', schema=None) as batch_op:
        batch_op.drop_index('ix_generations_status_next_check')
        batch_op.drop_index('ix_generations_quota')
        batch_op.drop_index('ix_generations_experiment')

    op.drop_table('generations')
    op.drop_table('comparisons')
    with op.batch_alter_table('asset_variants', schema=None) as batch_op:
        batch_op.drop_index('ix_variants_asset')

    op.drop_table('asset_variants')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index('ix_assets_experiment')

    op.drop_table('assets')
    op.drop_table('sessions')
    op.drop_table('idempotency_records')
    op.drop_table('experiments')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_target')

    op.drop_table('audit_events')
    op.drop_table('presets')
    op.drop_table('operators')
    # ### end Alembic commands ###
