"""A2: quota grants

Revision ID: ddcc479bce83
Revises: ed4948291cb6
Create Date: 2026-09-08 04:48:55.555999
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'ddcc479bce83'
down_revision: str | None = 'ed4948291cb6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quota_grants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('additional', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('granted_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quota_grants', schema=None) as batch_op:
        batch_op.create_index('ix_quota_grants_key', ['experiment_id', 'asset_id', 'provider'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quota_grants', schema=None) as batch_op:
        batch_op.drop_index('ix_quota_grants_key')

    op.drop_table('quota_grants')
    # ### end Alembic commands ###
