"""A2: worker state columns

Revision ID: ed4948291cb6
Revises: 8ea2e151cb68
Create Date: 2026-09-08 04:46:14.350030
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'ed4948291cb6'
down_revision: str | None = '8ea2e151cb68'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_result_ref', sa.Text(), nullable=True))
        # 既存行があっても通るよう server_default を付ける（仕様第8章の初期ポーリング10秒）
        batch_op.add_column(
            sa.Column(
                'poll_interval_seconds', sa.Integer(), nullable=False, server_default='10'
            )
        )
        batch_op.add_column(sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generations', schema=None) as batch_op:
        batch_op.drop_column('cancel_requested_at')
        batch_op.drop_column('poll_interval_seconds')
        batch_op.drop_column('provider_result_ref')

    # ### end Alembic commands ###
